### ISSUE TITLE
The user scrambling feature has a rounding error which makes a lot of duplicates

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-local_datacleaner#17]
The aim is to have a deterministic, but non reversible way of taking the existing names and mixing them up. We have N records and we have F fields we want to randomize.

The way this should work is to create a temporary table with a sorted list of names, and then using two prime numbers make pseudo random combinations from this list.

So if you had a bunch of real names like this:

id | First | Last
--|------------ | -------------
1 | David | Smith
2 | Nicholas | Hoobin
3 | Bill | Jones
4 | Daniel | Roperto 
5 | Brendan | Heywood
6 | Sarah | Bryce

In this case we have N = 6, and F = 2.

What we want is to find the smallest two adjacent prime numbers P1 and P2 which when multiplied gives us the number of records we have or higher. In this case 6 = 2 x 3. (note a quick heuristic is to start this search at it's square root and then work down / up from there. So ceil(root(6)) = 3).

For N = 100 records we'd have P1 = 9 and P2 = 11    (sqrt(100 = 10))

For N = 1000 records we'd get P1 = 31 and P2 = 37    (sqrt(1000) = 31)

For N = 10000 records we'd get P1 = 101 and P2 = 102    (sqrt(10000) = 100)

So we are going to create a temp table with 3 (the bigger prime) records. This process is the same regardless of F.

If we had 5 fields to randomize then F = 5, we want 5 prime numbers. So as well as P1 and P2 we just find the next couple primes higher than P1, P2, etc.

Now we create a temp table which has as many records as our highest prime. We only have P1 and P2, and P2 = 3. So we want 3 records in our temp table. Let's start by cloning the first 3 records from our real data into a temp table:

id | First | Last
--|------------ | -------------
1 | David | Smith
2 | Nicholas | Hoobin
3 | Bill | Jones

We don't want to be able to figure out who was who originally so lets sort each column independently:

id | First | Last
--|------------ | -------------
1 | Bill | Hoobin
2 | David | Jones
3 | Nicholas | Smith

Now we pick the index modulo 2 for the first column, and the modulo 3 for the second column (and so on if we had more columns) and then lookup what value this maps to in the temp table as our new scrambled value:

id | Old First | Old Last | id % P1 (2) | New First | id % P2 (3) | New Last
--|------------ | -------------|--|--|--|--
1 | David | Smith | 1 | Bill | 1 | Hoobin 
2 | Nicholas | Hoobin | 2 | David |  2 | Jones
3 | Bill | Jones | 1 | Bill | 3 | Smith
4 | Daniel | Roperto | 2 | David | 1 | Hoobin
5 | Brendan | Heywood | 1 | Bill | 2 | Jones
6 | Sarah | Bryce | 2 | David | 3 | Smith

And voila, we have now scrambled everyone! Everyone has a realistic name, the names cannot be easily reversed back to the original records, and because of the prime numbers we guarantee that everyone has a unique combination of names. Because it is a single sql update is it incredibly quick. And because we are sampling from our original names we get realistic data that looks familiar.

Note with a small N, there data does look repetitive, but for larger data-sets this deficiency fades away. If you have 1000 students, and typical course sizes of 30 students, then you shouldn't see too may duplicates within a course.

Also because it is deterministic if we re-run this each night we will get the same result so it's easier for a tester to use the same user again and again and not have it be wildly different each time (eg if we used pure random numbers).

**Comment by brendanheywood** [comment]
Also this whole scrambler thing should be a utility function in the local plugin and be given the table to operate on. We will want to reuse this on other tables in other cleaner subplugins

**Comment by roperto** [comment]
> What we want is to find the smallest two adjacent prime numbers P1 and P2 which when multiplied gives us the number of records we have or higher.

It is not trivial to find the minimum F prime factors that when multiplied become the desired product (or the closest higher number possible).

> (note a quick heuristic is to start this search at it's square root and then work down / up from there. So ceil(root(6)) = 3).

If more fields are used, we will need the cubic root or Nth root. If we have 25 fields, sqrt(25) = 5 then 5*7*11 = 385 (following prime numbers). In that case we needed 2x3x5=30 would be enough.

> Now we create a temp table which has as many records as our highest prime [...]

Due to the previous sorting, I think the correct table should be:

id | First | Last
--|------------ | -------------
1 | Bill | Jones
2 | Brendan | Heywood
3 | Daniel | Roperto

> We don't want to be able to figure out who was who originally so lets sort each column independently:

Still WIP, I will update here once as I go...

**Comment by brendanheywood** [comment]
Nope, nth root isn't needed and is overkill. You seem to be confusing the number of fields with the number of records. If you have 100 records and 5 fields to scramble then you need two main primes 9 and 11 > 100, then 13,17,19 to make up 5. Pick the biggest prime and then grab that many records into the temp table. Each scrambled field will use a different number of rows so the values in the bottom left of the table will be ignored.

and the sort method was also correct as is. You want to grab the first n as is, then sort, otherwise you end up with a sample biased towards the start of the alphabet

**Comment by roperto** [comment]
Hi

> What we want is to find the smallest two adjacent prime numbers P1 and P2 which when multiplied gives us the number of records we have or higher. In this case 6 = 2 x 3. (note a quick heuristic is to start this search at it's square root and then work down / up from there. So ceil(root(6)) = 3).

No problems, it works with sqrt(), I reverted to that implementation.

I don't understand why we need to start with the prime lower than sqrt(), instead of just getting the next one.
* sqrt(100 records) = 10, primes 9 and 11 = 99 (lower than record count)
* sqrt(6 records) = 2.4, primes 2 and 3 = 6 (exact number of records).

Now considering we have 3 fields instead of 2:
* sqrt(100 records) = 10, primes 9x11x13 = 1287 (higher than record count)
* sqrt(6 records) = 2.4, primes 2x3x5 = 30 (higher than record count).

As long as the highest prime number is lower than the number of DISTINCT records that will not be a problem, which is why sqrt() will work fine until we reach 1 million rows (I doubt we have tables to scramble with more than that).

From what I see, lowest prime numbers will get more repetitive names which is why Nth root was not a great idea, but why not get even higher numbers than sqrt(), as long as it is below the number of records?

> and the sort method was also correct as is. You want to grab the first n as is, then sort, otherwise you end up with a sample biased towards the start of the alphabet

True, it will be biased towards the first users of the table, which will probably look much better than lots of names starting with 'A'.

A question: Is there a quick way to sort a table by two columns (independently)? Just to be clear, if we "sort by first, last" we are sorting by one column, then the other, which is not independent.

After discussing a bit with Nick we got to a solution involving one temporary table per field, which will be used later in the join to update the original table with scrambled data. But I am still wondering if there is any trick to perform the sort you mentioned. 

> Now we pick the index modulo 2 for the first column, and the modulo 3 for the second column (and so on if we had more columns) and then lookup what value this maps to in the temp table as our new scrambled value:

That will require as many joins as we have different fields, right? I didn't implement that part yet, but it shouldn't be hard.

Cheers,
Daniel

**Comment by roperto** [comment]
I think the results table should be:

id | Old First | Old Last | id % P1 (2) + 1 | New First | id % P2 (3) + 1 | New Last
--|------------ | -------------|--|--|--|--
1 | David | Smith | 2 | David | 2 |  Jones
2 | Nicholas | Hoobin | 1 | Bill |  3 | Smith
3 | Bill | Jones | 2 | David | 1 | Hoobin
4 | Daniel | Roperto | 1 | Bill | 2 | Jones
5 | Brendan | Heywood | 2 |David  | 3 | Smith
6 | Sarah | Bryce | 1 | Bill | 1 | Hoobin

Note the +1 in the modules (as ids start from 1), then the new names are changed.

**Comment by roperto** [comment]
The only thing missing is when to get a prime number before the sqrt(). As of now it is already working for the output in my comment above.

**Comment by roperto** [comment]
Regardless of my questions above, Travis is green, the script seems to be working as expected.

Please let me know once you are happy with the code so I can merge into master.

Cheers,

**Comment by roperto** [comment]
Merged and released as 2.3.6
